group:
  - arcee

task: patents_qa_ppl

dataset_path: parquet
dataset_name: null

dataset_kwargs:
  data_files:
    test: s3://arcee-catch-all/patents_qa.parquet

output_type: loglikelihood_rolling
training_split: null
validation_split: null
test_split: test
fewshot_split: test

process_docs: !function patents.process_docs_qa
doc_to_text: !function patents.doc_to_text_qa
doc_to_target: !function patents.doc_to_target_qa

metadata:
  version: 2.0


