task: usmle
dataset_path: GBaker/MedQA-USMLE-4-options-hf
output_type: multiple_choice
training_split: train
validation_split: validation
test_split: test
doc_to_text: !function preprocess_usmle.doc_to_text
doc_to_target: !function preprocess_usmle.doc_to_target
doc_to_choice: !function preprocess_usmle.doc_to_choice
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  - version: 1.0
